### ISSUE TITLE
AttributeError: module 'plistlib' has no attribute 'Data'

### ISSUE THREAD

**Issue by mrfuturman** [ToBeDefined/TLocationPlugin#5]
Traceback (most recent call last):
  File "/Users/ccc/Desktop/TLocationPlugin/RunScript/inject_app_icon.py", line 172, in <module>
    plist_info = biplist.readPlist(plist_file_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/biplist/__init__.py", line 143, in readPlist
    raise InvalidPlistException(e)
biplist.InvalidPlistException: module 'plistlib' has no attribute 'Data'

升级python3.9后出现问题了

**Comment by ToBeDefined** [comment]
已修复
